
replicaCount: 2

image:
  repository: enricay/express-harness
  tag: 2bbcc48
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: harness.connectus.capplc.com
  path: /
  tls:
    enabled: true
    secretName: harness-tls