apiVersion: v1
kind: Service
metadata:
  name: harness
  labels:
    app: harness
spec:
  type: {{ .Values.service.type }}
  selector:
    app: harness
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http